name: Check for Quicklisp updates

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  check:
    name: Check for updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check the latest Quicklisp version
        run: |
          version=$(make version)
          quicklisp_version=$(make quicklisp_version)
          if [ "$version" = "$quicklisp_version" ]; then
            echo "No updates until the version '$quicklisp_version'."
          else
            echo "Found a new dist version '$quicklisp_version'"
            echo "Creating a deployment"
            curl -s -X POST \
              -H 'Authorization: token ${{ secrets.GH_DEPLOY_TOKEN }}' \
              -H 'Accept: application/vnd.github.v3+json' \
              https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments \
              -d "{\"ref\":\"master\",\"required_contexts\":[],\"payload\":{\"version\":\"${quicklisp_version}\"}}" \
                  > >(tee github_deployment)

            deployment_id=$(jq '.id' github_deployment)
            if [ "$deployment_id" = "null" ]; then
              echo "Failed to create a deployment"
              exit 1
            fi
            echo "Created a deployment $deployment_id"
          fi
