name: CI

on:
  push:
    branches:
      - '!master'

jobs:
  run_extract:
    name: Run extract to test
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: quickdocs
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Build Docker image
        run: |
          make docker_image
      - name: Extract the dist data
        env:
          BUCKET_BASE_URL: https://storage.googleapis.com/quickdocs-dist
        run: |
          make generate-index extract EXTRACT_ALL=1
