name: Extract Quicklisp dist data

on:
  push:
    paths: ['*']
  schedule:
    - cron: '0 15 * * *'

jobs:
  build_docker_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Docker image
        run: |
          make docker_image PUSH_IMAGE=1
  extract:
    name: Extract data
    runs-on: ubuntu-latest
    needs: build_docker_image
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Extract the dist data
        run: |
          make extract
      - uses: actions/upload-artifact@v2
        with:
          name: quicklisp-dist
          path: output
      - name: Upload to GCS
        if: github.ref == 'refs/heads/master'
        run: |
          make upload
