name: Extract Quicklisp dist data

on:
  push:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  extract:
    name: Extract data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Build Docker image
        run: |
          make docker_image
      - name: Push Docker image
        if: github.ref == 'refs/heads/master'
        run: |
          image_name=ghcr.io/quickdocs/quicklisp-dist-all
          version=$(docker images ghcr.io/quickdocs/quicklisp-dist-all | tail -n +2 | head -n 1 | awk '{ print $2 }')
          docker push "$image_name:$version"
      - name: Extract the dist data (push)
        if: ${{ github.event_name == 'push' }}
        env:
          BUCKET_BASE_URL: https://storage.googleapis.com/quickdocs-dist
        run: |
          make generate-index extract
      - name: Extract the dist data (schedule)
        if: ${{ github.event_name == 'schedule' }}
        env:
          BUCKET_BASE_URL: https://storage.googleapis.com/quickdocs-dist
        run: |
          [ `make version` != `make quicklisp_version` ] && make generate-index extract
      - name: Upload to GCS
        if: github.ref == 'refs/heads/master'
        run: |
          make upload
