name: Extract Quicklisp dist data

on:
  push:
    paths: ['*']
  schedule:
    - cron: '0 15 * * *'

jobs:
  build_docker_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Docker image
        run: |
          make docker_image
      - name: Save the Docker image
        run: |
          image_name=ghcr.io/quickdocs/quicklisp-dist-all
          docker save $image_name > /tmp/docker-image.tar
      - name: Upload the image as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: /tmp/docker-image.tar
  extract:
    name: Extract data
    runs-on: ubuntu-latest
    needs: build_docker_image
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Download an artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: /tmp
      - name: Load the Docker image
        run: |
          docker load --input /tmp/docker-image.tar
          docker image ls -a
      - name: Extract the dist data
        env:
          BUCKET_BASE_URL: https://storage.googleapis.com/quickdocs-dist
        run: |
          make extract
      - name: Upload to GCS
        if: github.ref == 'refs/heads/master'
        run: |
          make upload
  push_docker_image:
    name: Push Docker image
    runs-on: ubuntu-latest
    needs: build_docker_image
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Download an artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: /tmp
      - name: Load the Docker image
        run: |
          docker load --input /tmp/docker-image.tar
          docker image ls -a
      - name: Push Docker image
        run: |
          image_name=ghcr.io/quickdocs/quicklisp-dist-all
          version=$(docker images ghcr.io/quickdocs/quicklisp-dist-all | tail -n +2 | head -n 1 | awk '{ print $2 }')
          docker push "$image_name:$version"
  clean:
    runs-on: ubuntu-latest
    if: always()
    needs: [extract, push_docker_image]
    steps:
      - name: Delete the artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: docker-image
          failOnError: false
