name: Invoke extraction

on:
  push:
    branches:
      - master

jobs:
  invoke_extract:
    name: Invoke full extraction
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Invoke extraction
        run: |
          quicklisp_version=$(make quicklisp_version)
          echo "Creating a deployment"
          curl -s -X POST \
            -H 'Authorization: token ${{ secrets.GH_DEPLOY_TOKEN }}' \
            -H 'Accept: application/vnd.github.v3+json' \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments \
            -d "{\"ref\":\"master\",\"required_contexts\":[],\"payload\":{\"version\":\"${quicklisp_version}\",\"target\":\"all\"}}" \
                > >(tee github_deployment)

          deployment_id=$(jq '.id' github_deployment)
          if [ "$deployment_id" = "null" ]; then
            echo "Failed to create a deployment"
            exit 1
          fi
