name: Invoke update

on: deployment_status

jobs:
  invoke_update:
    name: Invoke DB update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create a deployment of quickdocs/dist-updater
        run: |
          quicklisp_version=$(make quicklisp_version)
          deployment_state=$(jq -r '.deployment_status.state' $GITHUB_EVENT_PATH)
          if [ "$deployment_state" = "success" ]; then
            curl -s -X POST \
              -H 'Authorization: token ${{ secrets.GH_DEPLOY_TOKEN }}' \
              -H 'Accept: application/vnd.github.v3+json' \
              https://api.github.com/repos/quickdocs/dist-updater/deployments \
              -d "{\"ref\":\"master\",\"required_contexts\":[],\"payload\":{\"version\":\"${quicklisp_version}\"}}" \
          fi
